[package]
name = "webadev-bundle"
version = "0.1.0"
edition = "2024"
default-run = "bundle"

[lib]
path = "rust/mod.rs"

[[bin]]
name = "bundle"
path = "rust/bin/bundle.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
lightningcss = "1.0.0-alpha.72"
parcel_sourcemap = "2.1.1"
rolldown = "1"
tokio = { version = "1", features = ["full"] }
webadev = "0.3"