[package]
name = "bundla"
version = "0.1.0"
edition = "2024"
description = "Bundle Html, Css, and Js with live-reload for dev, or with minification, hashed filenames for release"
license = "MIT"
repository = "https://github.com/francoisromain/bundla"
homepage = "https://github.com/francoisromain/bundla"
rust-version = "1.88"
keywords = ["bundle", "live-reload", "web", "development", "watch"]
categories = ["development-tools"]
exclude = ["client/**", "sessions/**"]

[dependencies]
clap = { version = "4", features = ["derive"] }
lightningcss = "1.0.0-alpha.72"
open = "5"
parcel_sourcemap = "2.1.1"
rolldown = "1"
tokio = { version = "1", features = ["full"] }
webadev = "0.5"
